## **Column Transformer**

1. Applies different preprocessing techniques to different columns in one step.
   
2. Useful when a dataset has mixed feature types (numerical + categorical).


3. Fits all transformers on the training data and applies the same transformations to the test data.

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('docs/Lecture-015-covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
82   24    Male   98.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
34   74    Male  102.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
86   25    Male  104.0    Mild  Bangalore
21   73    Male   98.0    Mild  Bangalore
79   48  Female  103.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata

[80 rows x 5 columns]

## **Column Transformer**

`'tnf1'` → Name of this transformer (can be any name).

`StandardScaler()` → Transformation to apply.

`['age', 'salary']` → Columns on which the transformation is applied.


`remainder ='passthrough'` --> Keeps all remaining columns unchanged.

`remainder='drop'` --> Drops all columns that are not explicitly listed.

In [8]:
from sklearn.compose import ColumnTransformer

In [10]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [11]:
transformer.fit_transform(X_train).shape

(80, 7)

In [12]:
transformer.transform(X_test).shape

(20, 7)

`fit_transform()` → Learn preprocessing parameters from training data and transform it.

`transform()` → Apply the same learned transformations to the test data as well.