In [1]:
import numpy as np 
import pandas as pd

**Pivot Tables**

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    723     73   John  January      Q1
1  2023-01-02       B   West    470     52   Mary  January      Q1
2  2023-01-03       C  North    908     68    Bob  January      Q1
3  2023-01-04       D  South    937     41  Alice  January      Q1
4  2023-01-05       A   East    334     33   John  January      Q1
5  2023-01-06       B   West    943     24   Mary  January      Q1
6  2023-01-07       C  North    140     88    Bob  January      Q1
7  2023-01-08       D  South    185     85  Alice  January      Q1
8  2023-01-09       A   East    925     71   John  January      Q1
9  2023-01-10       B   West    674     97   Mary  January      Q1
10 2023-01-11       C  North    428     66    Bob  January      Q1
11 2023-01-12       D  South    618     13  Alice  January      Q1
12 2023-01-13       A   East    485     45   John  January      Q1
13 2023-01-14       B   West    774     61   Mary  January      Q1
14 2023-01-15       C  North    198     75    Bob  January      Q1
15 2023-01-16       D  South    812     71  Alice  January      Q1
16 2023-01-17       A   East    855     63   John  January      Q1
17 2023-01-18       B   West    355     89   Mary  January      Q1
18 2023-01-19       C  North    980     13    Bob  January      Q1
19 2023-01-20       D  South    676     19  Alice  January      Q1

In [4]:
pd.pivot_table(df, values='Sales', index='Region', aggfunc='median')

        Sales
Region
East    723.0
North   428.0
South   676.0
West    674.0

In [5]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     664.4    NaN    NaN    NaN  57.0   NaN   NaN   NaN
North      NaN    NaN  530.8    NaN   NaN   NaN  62.0   NaN
South      NaN    NaN    NaN  645.6   NaN   NaN   NaN  45.8
West       NaN  643.2    NaN    NaN   NaN  64.6   NaN   NaN

**Cross Tabs**

In [6]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0